import type { Metadata } from "next";
import Image from 'next/image';
import { Inter } from "next/font/google";
import "./globals.css";
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuIndicator,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  NavigationMenuViewport,
} from "@/components/ui/navigation-menu";
import { Link } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex items-center">
          <div>
            <Image
            src="/Hiit.svg"
            width={160}
            height={160}
            alt="Hiit Logo"
            />
          </div>

          <div className="grow text-center">
              <h1 className="text-4xl italic font-bold">Health Impact, Inspire Trust</h1>
          </div>

        </header>
        <nav className="p-10">
          <ul className="flex justify-evenly">
            <li>
              <a href="/">Inicio</a>
            </li>
            <li>
              <a href="/producto">Hombres</a>
            </li>
            <li>
              <a href="/producto">Mujeres</a>
            </li>
            <li>
              <a href="/">Inicio</a>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
